#spring.datasource.platform=h2

spring:

  datasource:
    url: jdbc:mysql://AWS-end-point:3306/spring
    username: spring
    password: springboot
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect